### PR TITLE
Wifi hotspot working

### PR DESCRIPTION
**Pull request by adrianalin**
This PR is still in progress, need to also test the wifi client functionality. The wifi hotspot seems to work (at least i can see it showing up).

### CODE REVIEW

**Comment by matt2005** [comment]
Great, how about we discuss and plan a roadmap going forward, i feel we are working towards a common goal.

**Comment by matt2005** [comment]
@adrianalin [roadmap](https://github.com/matt2005/csng_yocto/wiki/Roadmap) 
[Project idea](https://github.com/matt2005/csng_yocto/projects/1)

Would you be willing to work together on this?

**Comment by adrianalin** [comment]
@matt2005 yes we can work together on this. It's good to have a roadmap and maybe issues(?) so we don't work on the exact same thing in order to avoid conflicts. There is a crankshaft / openauto chat to join?

**Comment by matt2005** [comment]
Yes I have a slack group for opencardev. I'll email you an invite.

Did you have a look at the roadmap?

**Comment by adrianalin** [comment]
Yes, i looked on the roadmap, it's good to have it. 

I also looked on the commits you did on main branch. Have you looked on this pull request? Seems to me we are trying to do the exact same thing.

**Comment by adrianalin** [comment]
Should i continue working on this wifi hotspot / wifi client functionality, or maybe should i focus on something else?

**Comment by matt2005** [comment]
Yes please continue with wifi. I've not touched it yet, I was just prepping the system for the crankshaft configs.

**Review by matt2005 — CHANGES_REQUESTED** [review]
Actually I'm going to merge this as i've got additional changes to make on top for the other scripts.

**Pull request merged**
